version: '3.8'

services:
  # Service 1: Database PostGIS
  db:
    image: postgis/postgis:15-3.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=watchstore_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # Dòng này giúp máy Mac chip M1/M2 không bị lỗi
    platform: linux/amd64

  # Service 2: Django Web App
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=watchstore_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=adminpass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data: